apiVersion: v1
kind: Service

metadata:
  name: library-service
  labels:
    app: library-platform

spec:
  type: NodePort

  selector:
    app: library-platform

  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30080